spring.profiles.active: production

server:
  port: {{ pillar['wheat']['port'] }}

wheatserver.general:
  tileSize: 512
  imageFormat: png
  expressionFieldPrefix: VAR
  fontName: "Droid Sans"
  sessionKey: "123456"

wheatserver.mongo:
  database: {{ pillar['myapp']['database'] }}
  port: {{ pillar['mongodb']['port'] }}
  hosts: ["{{ salt.mine.get('roles:mongodb', 'private_ip', expr_form='grain').items() | join('","', attribute="1") }}"]