spring.profiles.active: production

myappworkers.aws:
    accessId: {{ pillar['wheat']['workers']['aws']['credentials']['key'] }}
    secretKey: {{ pillar['wheat']['workers']['aws']['credentials']['secretKey'] }}
    domain: {{ pillar['myapp']['aws']['swf']['domain'] }}
    taskList: JavaList
    nodeTaskList: NodeList
    endpoint: "https://swf.{{ pillar['wheat']['workers']['aws']['region'] }}.amazonaws.com"

myappworkers.general:
    wundergroundApiKey: {{ pillar['wheat']['workers']['wunderground'] }}

myappworkers.mongo:
  database: {{ pillar['myapp']['database'] }}
  port: {{ pillar['mongodb']['port'] }}
  hosts: ["{{ salt.mine.get('roles:mongodb', 'private_ip', expr_form='grain').items() | join('","', attribute="1") }}"]